Repository Xrayya/Nutri-Byte, pull requests merged in 2024-01, with the labels that each got.

#4 1 define design system
  frontend/lib/app/core/theme/colors.dart
  frontend/lib/app/core/theme/theme_data.dart
Labels: enhancement

#5 1 define design system
  frontend/lib/app/core/theme/colors.dart
  frontend/lib/app/core/theme/theme_data.dart
  frontend/lib/app/core/utils/color_utils.dart
  frontend/lib/main.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: enhancement

#6 2 setup font
  frontend/fonts/Signika/OFL.txt
  frontend/fonts/Signika/static/Signika-Bold.ttf
  frontend/fonts/Signika/static/Signika-Light.ttf
  frontend/fonts/Signika/static/Signika-Medium.ttf
  frontend/fonts/Signika/static/Signika-Regular.ttf
  frontend/fonts/Signika/static/Signika-SemiBold.ttf
  frontend/lib/app/core/theme/theme_data.dart
  frontend/pubspec.yaml
Labels: enhancement

#10 8 develop home
  frontend/images/placeholder.png
  frontend/lib/app/data/models.dart
  frontend/lib/app/modules/home/dashboard/bindings/dashboard_binding.dart
  frontend/lib/app/modules/home/dashboard/controllers/dashboard_controller.dart
  frontend/lib/app/modules/home/dashboard/views/dashboard_view.dart
  frontend/lib/app/modules/home/detail_nutrition/bindings/detail_nutrition_binding.dart
  frontend/lib/app/modules/home/detail_nutrition/controllers/detail_nutrition_controller.dart
  frontend/lib/app/modules/home/detail_nutrition/views/detail_nutrition_view.dart
  frontend/lib/app/modules/home/views/home_view.dart
  frontend/lib/app/routes/app_pages.dart
  frontend/lib/app/routes/app_routes.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: enhancement

#14 doc: application and team description
  README.md
Labels: documentation

#15 docs: add screenshots
  README.md
Labels: documentation

#18 feat(home): UI styling, add button to go to another pages
  frontend/lib/app/data/services/user_repository.dart
  frontend/lib/app/modules/home/controllers/home_controller.dart
  frontend/lib/app/modules/home/detail_nutrition/views/detail_nutrition_view.dart
  frontend/lib/app/modules/home/quests/bindings/quests_binding.dart
  frontend/lib/app/modules/home/quests/controllers/quests_controller.dart
  frontend/lib/app/modules/home/quests/views/quests_view.dart
  frontend/lib/app/modules/home/rewards/bindings/rewards_binding.dart
  frontend/lib/app/modules/home/rewards/controllers/rewards_controller.dart
  frontend/lib/app/modules/home/rewards/views/rewards_view.dart
  frontend/lib/app/modules/home/views/home_view.dart
  frontend/lib/app/routes/app_pages.dart
  frontend/lib/app/routes/app_routes.dart
  frontend/lib/app/widgets/fab_with_button.dart
Labels: enhancement

#21 19 slice quest page
  frontend/lib/app/data/models/chart_data.dart
  frontend/lib/app/data/models/quest.dart
  frontend/lib/app/modules/home/controllers/home_controller.dart
  frontend/lib/app/modules/home/detail_nutrition/controllers/detail_nutrition_controller.dart
  frontend/lib/app/modules/home/detail_nutrition/views/detail_nutrition_view.dart
  frontend/lib/app/modules/home/quests/controllers/quests_controller.dart
  frontend/lib/app/modules/home/quests/views/quests_view.dart
  frontend/lib/app/modules/home/views/home_view.dart
  frontend/lib/app/widgets/fab_with_button.dart
  frontend/lib/app/widgets/nutribyte_back_button.dart
Labels: enhancement

#23 20 slice reward page
  frontend/assets/images/gift.png
  frontend/lib/app/core/injection.dart
  frontend/lib/app/data/models/nutribyte_user.dart
  frontend/lib/app/data/models/reward.dart
  frontend/lib/app/data/models/reward_transaction.dart
  frontend/lib/app/data/provider/reward_provider.dart
  frontend/lib/app/data/provider/user_provider.dart
  frontend/lib/app/data/services/reward_repository.dart
  frontend/lib/app/modules/auth/REGISTER/views/register_view.dart
  frontend/lib/app/modules/home/controllers/home_controller.dart
  frontend/lib/app/modules/home/rewards/controllers/rewards_controller.dart
  frontend/lib/app/modules/home/rewards/views/rewards_view.dart
  frontend/lib/app/modules/home/scanfood/scannutrition/views/scannutrition_view.dart
  frontend/lib/app/modules/home/scanfood/views/scanfood_view.dart
  frontend/lib/app/modules/home/views/home_view.dart
Labels: enhancement

#24 22 slice profile page
  frontend/assets/images/dummy_pp.png
  frontend/lib/app/data/services/reward_repository.dart
  frontend/lib/app/modules/auth/REGISTER/controllers/register_controller.dart
  frontend/lib/app/modules/auth/REGISTER/views/register_view.dart
  frontend/lib/app/modules/auth/bindings/auth_binding.dart
  frontend/lib/app/modules/auth/controllers/auth_controller.dart
  frontend/lib/app/modules/auth/signin/views/signin_view.dart
  frontend/lib/app/modules/home/controllers/home_controller.dart
  frontend/lib/app/modules/home/detail_nutrition/controllers/detail_nutrition_controller.dart
  frontend/lib/app/modules/home/detail_nutrition/views/detail_nutrition_view.dart
  frontend/lib/app/modules/home/detailprofile/bindings/detailprofile_binding.dart
  frontend/lib/app/modules/home/detailprofile/controllers/detailprofile_controller.dart
  frontend/lib/app/modules/home/detailprofile/views/detailprofile_view.dart
  frontend/lib/app/modules/home/quests/views/quests_view.dart
  frontend/lib/app/modules/home/rewards/views/rewards_view.dart
  frontend/lib/app/modules/home/scanfood/views/scanfood_view.dart
  frontend/lib/app/modules/home/views/home_view.dart
  frontend/lib/app/modules/home/views/homesection_view.dart
  frontend/lib/app/modules/home/views/profilesection_view.dart
  frontend/lib/app/routes/app_pages.dart
  frontend/lib/app/routes/app_routes.dart
  frontend/lib/app/widgets/fab_with_button.dart
  frontend/lib/app/widgets/nutribyte_back_button.dart
Labels: bug, enhancement

#27 feat: add target nutrition calculation
  frontend/lib/app/core/utils/helper.dart
  frontend/lib/app/core/utils/nutrition_calc.dart
  frontend/lib/app/data/models/nutritions.dart
  frontend/lib/app/data/provider/user_provider.dart
  frontend/lib/app/data/services/user_repository.dart
  frontend/lib/app/modules/home/scanfood/scannutrition/controllers/scannutrition_controller.dart
Labels: enhancement

#32 25 implement calculation
  frontend/lib/app/modules/home/controllers/home_controller.dart
  frontend/lib/app/modules/home/views/homesection_view.dart
Labels: enhancement
